# Generated by Django 3.2.13 on 2023-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('deptofdoctor', models.CharField(default='', max_length=30)),
                ('doctor', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
